/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AnimeDetailsIdImport } from "./routes/anime-details/$id";
import { Route as PlayerIdImport } from "./routes/player/$id";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const PlayerIdRoute = PlayerIdImport.update({
  path: "/player/$id",
  getParentRoute: () => rootRoute,
} as any);

const AnimeDetailsIdRoute = AnimeDetailsIdImport.update({
  path: "/anime-details/$id",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/anime-details/$id": {
      id: "/anime-details/$id";
      path: "/anime-details/$id";
      fullPath: "/anime-details/$id";
      preLoaderRoute: typeof AnimeDetailsIdImport;
      parentRoute: typeof rootRoute;
    };
    "/player/$id": {
      id: "/player/$id";
      path: "/player/$id";
      fullPath: "/player/$id";
      preLoaderRoute: typeof PlayerIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/anime-details/$id": typeof AnimeDetailsIdRoute;
  "/player/$id": typeof PlayerIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/anime-details/$id": typeof AnimeDetailsIdRoute;
  "/player/$id": typeof PlayerIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/anime-details/$id": typeof AnimeDetailsIdRoute;
  "/player/$id": typeof PlayerIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/anime-details/$id" | "/player/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/anime-details/$id" | "/player/$id";
  id: "__root__" | "/" | "/anime-details/$id" | "/player/$id";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  AnimeDetailsIdRoute: typeof AnimeDetailsIdRoute;
  PlayerIdRoute: typeof PlayerIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnimeDetailsIdRoute: AnimeDetailsIdRoute,
  PlayerIdRoute: PlayerIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/anime-details/$id",
        "/player/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/anime-details/$id": {
      "filePath": "anime-details/$id.tsx"
    },
    "/player/$id": {
      "filePath": "player/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
